name: Auto deploy
on:
  push:
    branches:
      - master
jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      app: ${{ steps.filter.outputs.app }}
      admin: ${{ steps.filter.outputs.admin }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app:
              - 'app/**'
            admin:
              - 'admin/**'
  trigger-deploy-app:
    needs: changes
    if: ${{ needs.changes.outputs.app == 'true' }}
    uses: ./.github/workflows/deploy.yaml
    with:
      app: app
  deploy-admin:
    needs: changes
    if: ${{ needs.changes.outputs.app == 'true' }}
    uses: ./.github/workflows/deploy.yaml
    with:
      app: admin
