name: Manual set config
on: workflow_dispatch
jobs:
  manual-set-config:
    steps:
      - uses: actions/checkout@v2
      - uses: Summ-Technologies/heroku-config@da7516dd182b82f84ca247c404f2780f81490001
        with:
          heroku_app_name: flok-backend-staging
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          envfile_path: admin/.env.prod
