name: Manual set config
on: workflow_dispatch
jobs:
  manual-set-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Summ-Technologies/heroku-config
        with:
          heroku_app_name: flok-backend-staging
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          envfile_path: admin/.env.prod
