name: Deploy
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string # either app or admin
    secrets:
      HEROKU_API_KEY:
        required: true
      PIP_EXTRA_INDEX_URL:
        required: true
env:
  HEROKU_APP_NAME: flok-test
jobs:
  deploy-app:
    if: ${{ inputs.app == 'app' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Summ-Technologies/heroku-config@master
        with:
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          envfile_path: admin/.env.prod
      - uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          email: "jared@goflok.com"
          dockerfile_directory: "./app/"
          dockerfile_name: "Dockerfile"
  deploy-admin:
    if: ${{ inputs.app == 'admin' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: flok-heroku-test2
          heroku_email: "jared@goflok.com"
          appdir: "admin"
          stack: "container"
          env_file: /.env.prod
