name: Manual deploy
on:
  workflow_dispatch:
    inputs:
      app:
        description: "The app to deploy"
        required: true
        type: choice
        options:
          - app
          - admin
jobs:
  manual-deploy-app:
    if: ${{ github.event.inputs.app == 'app'}}
    uses: ./.github/workflows/deploy.yml
    with:
      app: app
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      PIP_EXTRA_INDEX_URL: ${{ secrets.PIP_EXTRA_INDEX_URL }}
  manual-deploy-admin:
    if: ${{ github.event.inputs.app == 'admin'}}
    uses: ./.github/workflows/deploy.yml
    with:
      app: admin
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
