name: Manual deploy
on:
  workflow_dispatch:
    inputs:
      app:
        description: "The app to deploy"
        required: true
        type: choice
        options:
          - app
          - admin
jobs:
  manual-deploy-app:
    if: ${{ github.event.inputs.app == 'app'}}
    uses: ./.github/workflows/deploy.yaml
    with:
      app: app
  manual-deploy-admin:
    if: ${{ github.event.inputs.app == 'admin'}}
    uses: ./.github/workflows/deploy.yaml
    with:
      app: admin
